--- 
abstract: Reduce Perl code to as few charactes as possible
author: Adam Kennedy <cpan@ali.as>
build_requires: 
  File::Spec: 0.82
  Test::More: 0.47
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Perl-Squish
no_index: 
  directory: 
    - t.data
    - inc
    - t
requires: 
  PPI: 0.992
  perl: 5.005
version: 0.03
