name: Perl-Squish
version: 0.02
abstract: Reduce Perl code to as few charactes as possible
author: Adam Kennedy <cpan@ali.as>
license: perl
distribution_type: module
build_requires:
  Test::More: 0.47
  File::Spec: 0.82
requires:
  perl: 5.005
  PPI: 0.992
no_index:
  directory:
    - t.data
    - inc
generated_by: Module::Install version 0.36
